In [123]:
import os
import requests 
import json
import numpy as np
import time
from tabulate import tabulate
import pandas as pd
from datetime import timedelta, date, datetime
# from openpyxl import load_workbook
import warnings
warnings.filterwarnings("ignore")

In [124]:
def token_endpoint(credentials):
    url = "https://qh-api.corp.hertshtengroup.com/api/token/"
    res = requests.post(url, json=credentials, verify=False)
    if res.status_code == 200:
        # res_refresh = res.json()['refresh']
        res_access = res.json()['access']
    return res_access

credentials = {"username": "h.bhattacharyya@hertshtengroup.com", #your email id 
                "password": "wrM6HIgziSGSv79l" #your qh generated password
            }

if not os.path.exists('qhCredentials.json'):
    access_token = token_endpoint(credentials)
    credentials['token'] = access_token
    with open('qhCredentials.json', 'w') as fp:
        json.dump(credentials, fp)

with open('qhCredentials.json') as f:
    data = json.load(f)
    token = data['token']
    print(token)

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoyMDc4MTM0MjUyLCJpYXQiOjE3NjI3NzQyNTIsImp0aSI6ImFlYmQxYWNiYThkZjQ5ZDlhNGNhM2I1MjRjOWU2OWFmIiwidXNlcl9pZCI6MjcxfQ.U5jHE9IyaKvi2UA--E4JBm6MFU5X3ZQmYFiztdwExGs

In [125]:
#making date and contrcat list
from datetime import datetime, timedelta

start_date = datetime(2026, 6, 9)
end_date = datetime(2026, 6,9)

dates = [
    start_date + timedelta(days=i)
    for i in range((end_date - start_date).days + 1)
]
print(dates)
contracts = ['WN26-U26','KWN26-U26']

[datetime.datetime(2026, 6, 9, 0, 0)]

In [126]:
def getData_TAS_v2(qh_contracts, dates_ls, strt_time: str, end_time: str):

    # Convert dates to string format
    dates_ls = [dt.strftime('%Y-%m-%d') for dt in dates_ls]

    combined_df = pd.DataFrame()
    url = "https://qh-api.corp.hertshtengroup.com/api/v2/tas/"

    headers = {
        "Accept": "application/json",
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json"
    }

    # Build products list dynamically for multiple contracts
    products_payload = [
        {
            "id": contract,
            "dates": dates_ls,
            "start": strt_time,
            "end": end_time
        }
        for contract in qh_contracts
    ]

    payload = {
        "products": products_payload
    }

    print("Requested contracts:", qh_contracts)
    print("Requested dates:", dates_ls)

    time.sleep(0.5)

    response = requests.post(url, headers=headers, json=payload)

    print("Initial API status:", response.status_code)

    if response.ok:

        response_json = response.json()

        print("Keys in response:", response_json.keys())
        print("Rows in first page:", len(response_json.get("data", [])))
        print("Total pages reported:", response_json.get("total_pages"))
        print("Next page URL:", response_json.get("next"))

        if response_json != {} and 'data' in response_json:

            df = pd.DataFrame(response_json['data'])

            print("Rows added from first page:", len(df))

            combined_df = pd.concat([combined_df, df], ignore_index=True)

            num_pages = response_json.get('total_pages', 1)

            if num_pages >= 2:

                next_url = response_json.get('next')

                for page in range(2, num_pages + 1):

                    if next_url and next_url != "None":

                        print(f"Fetching page {page} from:", next_url)

                        retry = 0

                        while retry < 5:

                            time.sleep(6)  # prevent rate limit

                            next_response = requests.post(
                                next_url,
                                headers=headers,
                                json=payload
                            )

                            print("Page status:", next_response.status_code)

                            if next_response.status_code == 200:
                                break

                            if next_response.status_code == 429:
                                print("Rate limit hit. Waiting 5 seconds...")
                                time.sleep(5)
                                retry += 1
                                continue

                            print("API error occurred.")
                            return combined_df

                        if next_response.ok:

                            next_json = next_response.json()

                            print("Rows in this page:", len(next_json.get("data", [])))
                            print("Next URL:", next_json.get("next"))

                            if 'data' in next_json:

                                next_df = pd.DataFrame(next_json['data'])

                                combined_df = pd.concat(
                                    [combined_df, next_df],
                                    ignore_index=True
                                )

                            next_url = next_json.get('next')

                        else:
                            print("Pagination stopped due to API error.")
                            break

            print("Final rows collected:", len(combined_df))

            return combined_df

    else:
        print(f"API Error: {response.status_code}")
        print(response.text)

    return pd.DataFrame()

In [127]:
df_tas = getData_TAS_v2(contracts, dates, '00:00:00', '23:59:59')

Requested contracts: ['WN26-U26', 'KWN26-U26']
Requested dates: ['2026-06-09']
Initial API status: 200
Keys in response: dict_keys(['status', 'page', 'total_pages', 'page_size', 'total_rows', 'next', 'previous', 'data'])
Rows in first page: 7803
Total pages reported: 1
Next page URL: None
Rows added from first page: 7803
Final rows collected: 7803

In [128]:
df_tas.head()
df=df_tas.copy()

In [129]:
daily_ohlc = (
    df.assign(timestamp=pd.to_datetime(df['timestamp']))
      .set_index('timestamp')
      .groupby('instrument')['price']
      .resample('D')
      .ohlc()
      .reset_index()
)

daily_ohlc["date"] = pd.to_datetime(
    daily_ohlc["timestamp"]
).dt.date

In [130]:
daily_ohlc.head()

  instrument                 timestamp   open   high    low  close        date
0  KWN26-U26 2026-06-09 00:00:00+00:00 -10.00  -8.75 -10.25  -9.50  2026-06-09
1   WN26-U26 2026-06-09 00:00:00+00:00 -12.25 -11.00 -12.50 -11.25  2026-06-09

In [131]:
ohlc_csv = "vap_dashboard_ohlc.csv"

if os.path.exists(ohlc_csv):

    existing = pd.read_csv(ohlc_csv)

    existing["date"] = pd.to_datetime(
        existing["date"]
    ).dt.date

    daily_ohlc["date"] = pd.to_datetime(
        daily_ohlc["date"]
    ).dt.date

    existing = existing[
        ~existing["date"].isin(
            daily_ohlc["date"].unique()
        )
    ]

    ohlc_final = pd.concat(
        [existing, daily_ohlc],
        ignore_index=True
    )

else:

    ohlc_final = daily_ohlc.copy()

ohlc_final.to_csv(
    ohlc_csv,
    index=False
)

In [132]:
df = df_tas.copy()

df["date"] = pd.to_datetime(
    df["timestamp"]
).dt.date

In [133]:
df["buy_qty"] = np.where(
    df["side"] == 1,
    df["qty"],
    0
)

df["sell_qty"] = np.where(
    df["side"] == -1,
    df["qty"],
    0
)

In [134]:
vap = (
    df.groupby(
        ["date","instrument","price"],
        as_index=False
    )
    .agg(
        total_volume=("qty","sum"),

        buying_volume=("buy_qty","sum"),

        selling_volume=("sell_qty","sum")
    )
)

In [135]:
vap.head()

         date instrument  price  total_volume  buying_volume  selling_volume
0  2026-06-09  KWN26-U26 -10.25            57              0              57
1  2026-06-09  KWN26-U26 -10.00           458            242             216
2  2026-06-09  KWN26-U26  -9.75           591            391             200
3  2026-06-09  KWN26-U26  -9.50          4006           1412            2594
4  2026-06-09  KWN26-U26  -9.25         11929           5449            6480

In [136]:
vap['delta']=vap['buying_volume']-vap['selling_volume']

In [137]:
import os
import pandas as pd

csv_file = "vap_dashboard_main.csv"

if os.path.exists(csv_file):

    existing = pd.read_csv(csv_file)

    # ensure same datatype
    existing["date"] = pd.to_datetime(
        existing["date"]
    ).dt.date

    vap["date"] = pd.to_datetime(
        vap["date"]
    ).dt.date

    # dates present in newly downloaded data
    dates_to_replace = vap["date"].unique()

    # remove old records for those dates
    existing = existing[
        ~existing["date"].isin(dates_to_replace)
    ]

    # append fresh data
    combined = pd.concat(
        [existing, vap],
        ignore_index=True
    )

else:

    combined = vap.copy()

combined = combined.sort_values(
    ["date", "instrument", "price"]
)

combined.to_csv(
    csv_file,
    index=False
)

print("Rows saved:", len(combined))
print("Dates updated:", vap["date"].nunique())

Rows saved: 87
Dates updated: 1

In [138]:
dup = vap.duplicated(
    subset=[
        "date",
        "instrument",
        "price"
    ]
)

print(dup.sum())

0

In [139]:
daily_ohlc.head()

  instrument                 timestamp   open   high    low  close        date
0  KWN26-U26 2026-06-09 00:00:00+00:00 -10.00  -8.75 -10.25  -9.50  2026-06-09
1   WN26-U26 2026-06-09 00:00:00+00:00 -12.25 -11.00 -12.50 -11.25  2026-06-09

In [140]:
print(pd.read_csv("vap_dashboard_main.csv").head())
print(pd.read_csv("vap_dashboard_ohlc.csv").head())

         date instrument  price  total_volume  buying_volume  selling_volume  \
0  2026-06-01  KWN26-U26 -11.75          3421            451            2970
1  2026-06-01  KWN26-U26 -11.50          6236           3373            2863
2  2026-06-01  KWN26-U26 -11.25          2050           1334             716
3  2026-06-01  KWN26-U26 -11.00           301            301               0
4  2026-06-01   WN26-U26 -13.25           151              0             151

   delta
0  -2519
1    510
2    618
3    301
4   -151
  instrument timestamp  open  high  low  close date  price  total_volume  \
0  KWN26-U26       NaN   NaN   NaN  NaN    NaN  NaN  -9.75         591.0
1  KWN26-U26       NaN   NaN   NaN  NaN    NaN  NaN  -9.50        4006.0
2  KWN26-U26       NaN   NaN   NaN  NaN    NaN  NaN  -9.25       11929.0
3  KWN26-U26       NaN   NaN   NaN  NaN    NaN  NaN  -9.00        2985.0
4  KWN26-U26       NaN   NaN   NaN  NaN    NaN  NaN  -8.75         246.0

   buying_volume  selling_volume   delta
0          391.0           200.0   191.0
1         1412.0          2594.0 -1182.0
2         5449.0          6480.0 -1031.0
3         2299.0           686.0  1613.0
4          246.0             0.0   246.0

In [141]:
import os

os.system("git add vap_dashboard_main.csv vap_dashboard_ohlc.csv")
os.system('git commit -m "VAP update"')
os.system("git push")

0